[package]
name = "rgrep"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.1.0"
glob = "0.3.1"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.10.6"
thiserror = "1.0.63"
