[package]
name = "xunmi-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "xunmia"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module"] }
serde_json = "1.0.127"
xunmi = "0.2.1"

[build-dependencies]
pyo3-build-config = "0.22.2"
